#!/bin/sh

find /home/dist/nodejs/ \
  -mindepth 2 \
  \( -type f -o -type d \) \
  -regextype posix-extended \
  ! -regex '/home/dist/nodejs/[a-z0-9-]*/index.(tab|json)' \
  -user dist \
  -mtime +7 \
  -exec chown root.root '{}' \;
