---

- name: Create C:\TEMP directory
  win_file: path='C:\TEMP' state=directory

- name: Python | Download Python 2 MSI
  win_get_url:
    url: 'https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi'
    dest: 'C:\TEMP\python.msi'
  tags: [download, python]

- name: Python | Install Python 2
  # ADDLOCAL=ALL means install all features, including appending python to the path
  raw: 'msiexec /i C:\TEMP\python.msi /qn ADDLOCAL=ALL
        /l*v C:\TEMP\python_install_log.txt'
  tags: [install, python]

- name: Java | Download Java 8
  win_get_url:
    url: 'http://javadl.sun.com/webapps/download/AutoDL?BundleId=109708'
    dest: 'C:\TEMP\java.exe'
  tags: [download, java]

- name: Java | Install Java 8
  raw: 'C:\TEMP\java.exe /s SPONSORS=0'
  tags: [install, java]

- name: Git | Download Git
  win_get_url:
    url: 'https://github.com/git-for-windows/git/releases/download/v2.6.0.windows.1/Git-2.6.0-64-bit.exe'
    dest: 'C:\TEMP\git.exe'
  tags: [download, git]

- name: Git | Copy Git Install Configuration
  win_copy: src='./resources/git_conf.inf' dest='C:\TEMP\git_conf.inf'
  tags: [install, git]

- name: Git | Install Git
  raw: 'C:\TEMP\git.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
        /LOADINF=C:\TEMP\git_conf.inf /LOG=C:\TEMP\git_install_log.txt
        /SAVEINF=C:\TEMP\git_install_log_inf.inf'
  tags: [install, git]

- name: Git | Enable long paths
  raw: 'git config --global core.longpaths true'
  tags: [install, git]

- name: GYP | Check if GYP is already cloned
  win_stat: path='C:\gyp'
  register: gyp_stat
  tags: [download, gyp]

- name: GYP | Clone GYP repository
  # Necessary for libuv test job
  raw: 'git clone https://chromium.googlesource.com/external/gyp C:\gyp'
  when: not gyp_stat.stat.exists
  tags: [download, gyp]

- name: Create C:\node-icu directory
  win_file: path='C:\\node-icu' state=directory

- name: ICU | Download ICU2C 54 zip
  win_get_url:
    url: 'http://download.icu-project.org/files/icu4c/54.1/icu4c-54_1-src.zip'
    dest: 'C:\node-icu\icu4c-54_1-src.zip'
  tags: [download, icu]

- name: ICU | Download ICU2C 55 zip
  win_get_url:
    url: 'http://download.icu-project.org/files/icu4c/55.1/icu4c-55_1-src.zip'
    dest: 'C:\node-icu\icu4c-55_1-src.zip'
  tags: [download, icu]

- name: ICU | Download ICU2C 56 zip
  win_get_url:
    url: 'http://download.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.zip'
    dest: 'C:\node-icu\icu4c-56_1-src.zip'
  tags: [download, icu]

- name: Jenkins | Download Jenkins Icon
  win_get_url:
    url: 'http://mirrors.jenkins-ci.org/art/jenkins-logo/favicon.ico'
    dest: 'C:\jenkins.ico'
  tags: [download, jenkins]

- name: Jenkins | Create jenkins.bat
  win_template: src='./resources/jenkins.bat' dest='C:\jenkins.bat'
  tags: [setup, jenkins]

- name: Jenkins | Create Jenkins Shortcuts
  script: './resources/Jenkins-Shortcuts.ps1'
  tags: [setup, jenkins]

- name: Automatic Logon | Setup Automatic Logon
  script: "./resources/Enable-Autologon.ps1 -UserName {{ ansible_ssh_user }} -Password {{ ansible_ssh_pass }}"
  tags: [setup, autologon]
