---

- name: centos7 | install epel
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: centos7 | install ius
  when: "arch != 'arm64' and arch != 'ppc64'"
  yum:
    name: "https://repo.ius.io/ius-release-el7.rpm"
    state: present

- name: centos7 | Add CloudLinux
  when: "arch != 'arm64' and arch != 'ppc64'"
  yum_repository:
    name: CloudLinux
    description: "Source for devtoolset-6"
    baseurl: https://repo.cloudlinux.com/cloudlinux/7/sclo/devtoolset-6/x86_64/
    gpgcheck: no
    state: present


- name: centos7 | install scl for devtoolset-6, devtoolset-8
  when: "arch != 'arm64'"
  yum:
    name: centos-release-scl
    state: present

- name: centos7 | aarch64 | install sclo repo
  when: "arch == 'arm64'"
  copy:
    src: "{{ role_path }}/files/centos-aarch-sclo.repo"
    dest: "/etc/yum.repos.d/centos-aarch-sclo.repo"
    mode: 0644

- name: centos7 | aarch64 | install sclo repo key
  when: "arch == 'arm64'"
  get_url:
    url: "https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-SCLo"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo"
    mode: 0644

# Clean up from when Python 3 was installed from source
- name: centos7 | ppc64 | clean python 3.7
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /tmp/Python-3.7
    - /usr/local/bin/2to3
    - /usr/local/bin/2to3-3.7
    - /usr/local/bin/idle3
    - /usr/local/bin/idle3.7
    - /usr/local/bin/pydoc3
    - /usr/local/bin/pydoc3.7
    - /usr/local/bin/python3
    - /usr/local/bin/python3.7
    - /usr/local/bin/python3.7-config
    - /usr/local/bin/python3.7m
    - /usr/local/bin/python3.7m-config
    - /usr/local/bin/python3-config
    - /usr/local/bin/pyvenv
    - /usr/local/bin/pyvenv-3.7
  when: "arch == 'ppc64'"
