- name: install gn build dependencies
  include_tasks: "{{ v8deps_include }}"
  loop_control:
    loop_var: v8deps_include
  with_first_found:
    - files:
      - "{{ role_path }}/tasks/partials/{{ os }}-{{ arch }}.yml"
      - "{{ role_path }}/tasks/partials/{{ os }}.yml"
      - "{{ role_path }}/tasks/partials/{{ os|stripversion }}.yml"
      skip: true  

- name: check existing gn
  ansible.builtin.command: "{{ gn_dest_dir }}/gn --version"
  changed_when: no
  failed_when: no
  register: gn_installed_version

- name: clone/update gn repository
  ansible.builtin.git:
    dest: "{{ gn_git_dir }}"
    repo: "https://gn.googlesource.com/gn"
    version: "{{ gn_version|default(omit) }}"
  become: "{{ gn_user|default(omit)|bool }}"
  become_user: "{{ gn_user|default(omit) }}"
  register: gn_git

# `gn --version` includes the first seven characters of the commit hash the
# binary was built from: e.g. 1620 (570aaed)
- name: check if gn needs to be rebuilt
  ansible.builtin.set_fact:
    rebuild_gn: "{{ not gn_installed_version.stdout|default('') is search(gn_git.after[:7]) }}"

- name: clean git checkout
  ansible.builtin.shell: git clean -fdX
  args:
    chdir: "{{ gn_git_dir }}"
  become: "{{ gn_user|default(omit)|bool }}"
  become_user: "{{ gn_user|default(omit) }}"
  when: rebuild_gn

# Requires a C++17 compiler.
- name: build gn
  ansible.builtin.shell: |
    python3 build/gen.py && \
    {{ gn_select_compiler }} && \
    ninja -C out && \
    out/gn_unittests
  args:
    chdir: "{{ gn_git_dir }}"
  become: "{{ gn_user|default(omit)|bool }}"
  become_user: "{{ gn_user|default(omit) }}"
  environment:
    CC: gcc
    CXX: g++
  when: rebuild_gn

- name: create symlink
  ansible.builtin.file:
    dest: "{{ gn_dest_dir }}/gn"
    src: "{{ gn_git_dir }}/out/gn"
    state: link
  become: "{{ gn_user|default(omit)|bool }}"
  become_user: "{{ gn_user|default(omit) }}"
  when: rebuild_gn
