---

compiler: {
  'rhel8': '. /opt/rh/gcc-toolset-12/enable'
}

gn_select_compiler: "{{ compiler[os]|default(compiler[os|stripversion])|default('true') }}"
gn_version: e2f38fa47b6a6e58e1d427e9d2af246a19cb980c

packages: {
  'rhel8': 'gcc-toolset-12'
}
