---

compiler: {
}

gn_select_compiler: "{{ compiler[os]|default(compiler[os|stripversion])|default('true') }}"
gn_version: 59107452bf84ce0d35bed08eecc1209e247b246b

packages: {
  ## rhel_llvm_version from baselayout vars
  'rhel8': 'clang-{{rhel_llvm_version}}'
}
