---

#
# aix: python2.7 is default
#

- name: check if pip exists
  stat:
    path: /usr/bin/pip
  register: pip_exists

- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /home/iojs/get-pip.py
  when: pip_exists.stat.exists == False

- name: install pip AIX71
  raw: /opt/freeware/bin/python3 /home/iojs/get-pip.py
  when: pip_exists.stat.exists == False and os == "aix71"

- name: install pip AIX72
  raw: /opt/bin/python3 /home/iojs/get-pip.py
  when: pip_exists.stat.exists == False and os == "aix72"

- name: create symbolic link AIX71
  file:
   src: "/opt/freeware/bin/pip"
   dest: "/usr/bin/pip"
   state: link
  when: pip_exists.stat.exists == False and os == "aix71"

- name: create symbolic link AIX72
  file:
   src: "/opt/bin/pip"
   dest: "/usr/bin/pip"
   state: link
  when: pip_exists.stat.exists == False and os == "aix72"

- name: install tap2junit
  pip: 
    name: tap2junit
    state: present
    executable: /usr/bin/pip
