#!/bin/sh

#
# PROVIDE: jenkins
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Configuration settings for jenkins in /etc/rc.conf:
#
# jenkins_enable (bool):
#   Set to "NO" by default.
#   Set it to "YES" to enable jenkins
#

. /etc/rc.subr

name="jenkins"
rcvar=jenkins_enable

load_rc_config ${name}

PATH="/usr/local/libexec/ccache:/usr/local/bin:${PATH}"
NODE_COMMON_PIPE="/home/iojs/test.pipe"

jenkins_jar="/home/iojs/slave.jar"
jenkins_log_file="/home/${jenkins_user}/${name}_console.log"
jenkins_args="-jar ${jenkins_jar} \
	-jnlpUrl ${jenkins_jnlpurl} \
	-secret ${jenkins_secret}"
jenkins_jobs="$(getconf NPROCESSORS_ONLN)"

# FreeBSD uses a java wrapper. Without full path pid monitoring won't work
procname=`cat /usr/local/etc/javavms | cut -d "#" -f 1`
pidfile="/var/run/${name}/${name}.pid"
monitor_pidfile="/var/run/${name}/${name}_monitor.pid"
command="/usr/sbin/daemon"
command_args="-r -p ${pidfile} -P ${monitor_pidfile} ${procname} \
	${jenkins_args} > ${jenkins_log_file} 2>&1"
env="PATH=${PATH} JOBS=${jenkins_jobs} OSTYPE=${OSTYPE} \
	NODE_COMMON_PIPE=${NODE_COMMON_PIPE} CC=cc CXX=c++"
required_files="${procname} ${jenkins_jar}"

start_precmd="${name}_prestart"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

jenkins_prestart() {
	if [ ! -f "${jenkins_log_file}" ]; then
		touch "${jenkins_log_file}"
		chown "${jenkins_user}:${jenkins_group}" "${jenkins_log_file}"
		chmod 640 "${jenkins_log_file}"
	fi
	if [ ! -d `basename ${pidfile}` ]; then
		install -d -o "${jenkins_user}" -g "${jenkins_group}" \
			-m 750 `basename ${pidfile}`
	fi

	if [ ! $jenkins_secret ]; then
		err 1 "You need to add a jenkins secret"
	fi
}

jenkins_start()
{
	check_startmsgs && echo -n "Starting ${name}"
	su -l ${jenkins_user} -c "${env} exec ${command} ${command_args}"
	echo .
}

jenkins_stop()
{
	if [ ! -f ${pidfile} ]; then
		echo "${name} isn't running."
	else
		echo -n "Stopping service: ${name}"
		kill `cat ${monitor_pidfile}`
		rm ${pidfile} ${monitor_pidfile}
		echo .
	fi
}

run_rc_command "$1"
