---

- name: create .aws directory
  ansible.builtin.file:
    dest: "{{ release_home_dir }}/.aws"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    state: directory
  
- name: copy credentials to deploy release artifacts
  ansible.builtin.copy:
    content: "{{ secrets.worker_credentials }}"
    dest: "{{ release_home_dir }}/.aws/credentials"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"

- name: write worker_config
  ansible.builtin.copy:
    dest: "{{ release_home_dir }}/.aws/config"
    src: "{{ role_path }}/files/worker_config"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
  when: not os|startswith("win")


# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Download awscliv2 installer
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: "/tmp"
    remote_src: true
    creates: '/tmp/aws'
    mode: 0755

- name: Run awscliv2 installer
  command:
  args:
    cmd: "/tmp/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install

- name: "Show awscliv2 installer output"
  debug:
    var: aws_install
    verbosity: 2