name: Check ORKA Packer Templates

on:
  push:
    paths:
      - 'orka/**/*.pkr.hcl'
  pull_request:
    paths:
      - 'orka/**/*.pkr.hcl'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Set up Packer
      uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 #v3.1.0

    - name: Create dummy Packer variables file
      working-directory: orka/templates
      run: |
        cat > variables.auto.pkrvars.hcl <<'EOF'
        orka_endpoint        = "https://mock-orka-endpoint"
        xcode_version = "mock-xcode_version"
        macos_version = "mock-macos_version"
        orka_source_image = "mock-orka_source_image"
        ssh_new_password = "mock-ssh_new_password"
        ssh_image_password  = "mock-ssh_image_password"
        ssh_new_public_key = "mock-new_public_key"
        EOF

    - name: Initialize Packer
      env:
        ORKA_AUTH_TOKEN: 'mock-orka-auth-token'
      run: |
        for file in $(find . -name '*.pkr.hcl'); do
          echo "Initializing $file"
          packer init $file || exit 1
        done
      working-directory: orka/templates

    - name: Validate Packer templates
      env:
        ORKA_AUTH_TOKEN: 'mock-orka-auth-token'
      working-directory: orka/templates
      run: |
        for file in $(find . -name '*.pkr.hcl'); do
          echo "Validating $file"
          packer validate -var-file=variables.auto.pkrvars.hcl "$file" || exit 1
        done